### ISSUE TITLE
Not able to change the footer links

### ISSUE THREAD

**Issue by anirtek** [agusmakmun/agusmakmun.github.io#14]
After forking your repo, there is a footer link to your github.io which I am trying to change. How can it be done?

**Comment by agusmakmun** [comment]
you can change it at `_layouts/default.html`, here is your [`footer links`](https://github.com/anirtek/anirtek.github.io/blob/master/_layouts/default.html#L148-L157)

**Comment by anirtek** [comment]
Yes. It's working now.
