### ISSUE TITLE
vulnerabilities in nokogiri 1.6.8.1

### ISSUE THREAD

**Issue by stiliyanv** [agusmakmun/agusmakmun.github.io#23]
nokogiri should be updated since there are known vulnerabilities in 1.6.8.1

<img width="792" alt="screen shot 2018-08-26 at 0 10 29" src="https://user-images.githubusercontent.com/3635470/44622630-e2631200-a8c4-11e8-89cd-d3ef2479709b.png">

**Comment by agusmakmun** [comment]
I already updated a new version, good catch @stiliyanv :+1:
