### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by vibrantabhi19** [agusmakmun/agusmakmun.github.io#3]
After making a gh-pages branch and navigating to https://username.github.io/agusmakmun.github.io/, the css are not loaded and only the contents are loaded. 
I als try to put the baseurl to 'agusmakmun.github.io' so as to tell it from where to load the css but still no success.
![screenshot from 2016-10-08 10-43-31](https://cloud.githubusercontent.com/assets/6832471/19210572/178f0cf2-8d44-11e6-9422-305d694bc77c.png)

**Comment by agusmakmun** [comment]
what happen when you change the url: https://github.com/vibrantabhi19/blog2/blob/gh-pages/_config.yml#L43

**Comment by vibrantabhi19** [comment]
After forking and hosting on gh-pages we have to redirect the js and the css to the base url (which is blog2 in my case). In the head tag I changed the path for stylesheet and javascript like "/static/css/" and "/static/js/" to "/blog2/static/css/" and "/blog2/static/js/" respectively. You can find this in here https://github.com/vibrantabhi19/blog2/blob/gh-pages/_layouts/default.html
Its working fine for now but I am facing lots of issues configuring the base url to every links.
If you wish, we can close this issue for now.
Thank you :)

**Comment by vibrantabhi19** [comment]
Alternatively, I think we should add {{site.baseurl}} to every link so that from next time it works fine just after adding the base url to the config_yml file.
For eg, After the css and js worked, all the links gave me a 404 error because it wasn't redirected to the base url so I put a {{site.baseurl}} tag in after every href.
It works fine even it nothing is configured as base url, it takes a blank attribute then.

**Comment by agusmakmun** [comment]
Of course you need to change your `site.url` and `site.baseurl`. other than that, on your repo need change to `*.github.io` eg: https://blog2.github.io, except if you config it to custom domain: https://help.github.com/articles/quick-start-setting-up-a-custom-domain/
