### ISSUE TITLE
Error while 'jekyll serve'

### ISSUE THREAD

**Issue by rahulrajpl** [agusmakmun/agusmakmun.github.io#48]
```
      Generating... 
                    done in 4.658 seconds.
jekyll 3.8.5 | Error:  uninitialized constant FFI::Platform::CPU

```
I got the above error while running 'jekyll serve'. Could you please help me solve this?

**Comment by earik87** [comment]
Hi! 

Looks like, the solution of your error exists already. 

https://github.com/jekyll/jekyll-help/issues/294

https://stackoverflow.com/questions/57105493/error-uninitialized-constant-ffiplatformcpu-on-starting-jekyll-server
