### ISSUE TITLE
How do I change the code highlighting in this theme?

### ISSUE THREAD

**Issue by rahulrajpl** [agusmakmun/agusmakmun.github.io#50]
Would you please let me know how to change the code highlighting to a different style in one shot. I don't want to dig into css sass etc. I know I can change it by going into details.

**Comment by earik87** [comment]
You should do the following in this [link](https://stackoverflow.com/questions/51750463/how-to-change-code-snippet-background-in-jekyll-blog?noredirect=1&lq=1)

This must be fixed in the main code.

**Comment by rahulrajpl** [comment]
Thanks. It helped.
