### ISSUE TITLE
Do i fork and rename this repo or just copy files to my repo(suhailvs.github.io)?

### ISSUE THREAD

**Issue by suhailvs** [agusmakmun/agusmakmun.github.io#68]
i would like to know what is best `fork and rename` or `copy files`?

this stackoverflow post describe my problem https://stackoverflow.com/q/17268394/2351696

thank you

**Comment by suhailvs** [comment]
i have an existing site: https://suhailvs.github.io so 

+ `fork and rename`: i will need to remove my repo before renaming 
+ `copy files`: this will be easy, since no need to remove my repo. but hard to copy updates from agusmakmun.github.io to my repo.

**Comment by agusmakmun** [comment]
@suhailvs both methods are similar, you can choose one of them to apply into your project. \
But, my suggestions is:

1. Backup an existing project & posts (into your local)
2. Delete your previous project
3. Fork and rename
4. Sync your previous posts for new project

**Comment by suhailvs** [comment]
Thank you. I am going to fork this repo.
